/**
 * Correct Balance workflow (Master Data & Account Management Refactor, Decision 1/2).
 *
 * The ONLY way FinanceOS ever changes accounts.current_balance in response to a user
 * saying "the real balance is X" — it never writes current_balance directly. Instead it
 * computes the signed difference and saves a normal, system-generated ADJUSTMENT
 * transaction through the exact same services/transaction.service.ts path every other
 * transaction uses, which posts it through the Account Posting Engine
 * (account-posting.service.ts) exactly like an Expense or a Transfer. Activity stays the
 * complete, honest explanation of every balance change; there is no second mutation path.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import * as accountRepository from "@/repositories/account.repository";
import * as projectRepository from "@/repositories/project.repository";
import * as transactionService from "@/services/transaction.service";
import { convertToBaseCurrency } from "@/services/finance/exchange.service";
import { generateReceiptId } from "@/services/transaction/receiptid.service";
import { GENERIC_PROJECT_NAME } from "@/domain/project";
import { TRANSACTION_TYPES } from "@/constants/transaction-types";

export class AccountNotFoundError extends Error {}
export class NoBalanceChangeError extends Error {}
export class ReasonRequiredError extends Error {}

export type BalanceCorrectionResult = {
  previousBalance: number;
  newBalance: number;
  difference: number;
  transactionId: string;
};

/**
 * Builds and saves a system-generated ADJUSTMENT transaction whose signed amount is
 * exactly `newBalance - currentBalance` (in the account's own currency), then posts it
 * through the normal engine — the Posting Engine's signed ADJUSTMENT rule (Decision 2)
 * applies the same +/- delta to current_balance that a real ledger entry would. `reason`
 * is mandatory (v1.8.0 Account Balance Adjustment) — it becomes the transaction's
 * merchant/reference text, so it's the user-authored explanation visible on the
 * transaction in Activity, not just an internal audit note.
 */
export async function correctAccountBalance(
  supabase: SupabaseClient,
  accountId: string,
  newBalance: number,
  reason: string
): Promise<BalanceCorrectionResult> {
  const trimmedReason = reason.trim();
  if (!trimmedReason) {
    throw new ReasonRequiredError("A reason is required to adjust the balance.");
  }

  const account = await accountRepository.getById(supabase, accountId);
  if (!account) {
    throw new AccountNotFoundError("Account not found.");
  }

  const previousBalance = Number(account.current_balance);
  const difference = round2(newBalance - previousBalance);
  if (difference === 0) {
    throw new NoBalanceChangeError("New balance matches the current balance — nothing to correct.");
  }

  const projects = await projectRepository.list(supabase);
  const genericProjectId = projects.find((p) => p.project_name === GENERIC_PROJECT_NAME)?.id ?? null;

  const { baseAmount, exchangeRate } = await convertToBaseCurrency(supabase, difference, account.currency);
  const today = new Date().toISOString().slice(0, 10);
  const balanceSummary = `Balance correction: ${fmt(previousBalance)} → ${fmt(newBalance)}`;

  const { header } = await transactionService.createTransaction(supabase, {
    header: {
      receipt_id: generateReceiptId(),
      transaction_date: today,
      merchant: trimmedReason,
      transaction_type: TRANSACTION_TYPES.ADJUSTMENT,
      primary_category: "Miscellaneous",
      source_account_id: accountId,
      target_account_id: null,
      project_id: genericProjectId,
      currency: account.currency,
      original_amount: difference,
      exchange_rate: exchangeRate,
      sgd_total_amount: baseAmount,
      comments: `${balanceSummary} — System-generated by Adjust Balance.`,
      status: "Confirmed",
    },
    items: [
      {
        item_description: "Balance correction",
        tags: null,
        item_group: null,
        search_keywords: null,
        primary_category: "Miscellaneous",
        secondary_category: null,
        qty: "1",
        unit: null,
        pack_size: null,
        unit_price: null,
        item_total: difference,
      },
    ],
  });

  return { previousBalance, newBalance, difference, transactionId: header.id };
}

function fmt(n: number): string {
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
